#--------------------------------------------------------------------#
#
# Directions data
#
# The list defined in this module is the data set that will be
# used in the "Follow Directions" demonstration.
#

# These are the instructions to be followed - what do they draw?
instructions = [
               ['Left', 3],
               ['Forward', 10],
               ['Left', 2],
               ['Forward', 24],
               ['Left', 1],
               ['Forward', 8],
               ['Left', 1],
               ['Forward', 24],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 20],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 24],
               ['Left', 1],
               ['Forward', 15],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 6],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 7],
               ['Left', 1],
               ['Forward', 3],
               ['Left', 3],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 4],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 4],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 4],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 6],
               ['Left', 3],
               ['Forward', 4],
               ['Left', 3],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 4],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 4],
               ['Left', 3],
               ['Forward', 2],
               ['Left', 3],
               ['Forward', 4],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 2],
               ['Left', 1],
               ['Forward', 6],
               ['Left', 1],
               ['Forward', 4]
               ]
